# Generated by Django 5.1.6 on 2025-06-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.AlterModelTable(
            name='user',
            table='profile',
        ),
    ]
